import { APP_PATHS } from './feature-paths';

export const EMPTY_TEXTS: Record<APP_PATHS, string> = {
  [APP_PATHS.POSTS]: 'No Posts Found',
  [APP_PATHS.CREATORS]: 'No Creators Found',
  [APP_PATHS.VAULTS]: 'No Vaults Found',
  [APP_PATHS.SHORTS]: 'No Shorts Found',
  [APP_PATHS.CHANNELS]: 'No Channels Found',
  [APP_PATHS.CATEGORIES]: 'No Categories Found',
  [APP_PATHS.PURCHASED]: 'No Purchased Items Found',
  [APP_PATHS.TRENDING]: 'No Trending Items Found',
  [APP_PATHS.TRENDING_CREATORS]: 'No Trending Creators Found',
  [APP_PATHS.TRENDING_VAULTS]: 'No Trending Vaults Found',
  [APP_PATHS.LIKED_POSTS]: 'No Liked Posts Found',
  [APP_PATHS.LIKED_PICTURES]: 'No Liked Pictures Found',
  [APP_PATHS.LIKED_VAULTS]: 'No Liked Vaults Found',
  [APP_PATHS.PROFILE]: 'No Profile Found',
  [APP_PATHS.REPORTS]: 'No Reports Found',
  [APP_PATHS.SETTINGS]: 'No Settings Found',
  [APP_PATHS.SUBSCRIPTIONS]: 'No Subscriptions Found',
  [APP_PATHS.NOTIFICATIONS]: 'No Notifications Found',
  [APP_PATHS.FOLLOWING]: 'No Following Found',
  [APP_PATHS.HISTORY]: 'No History Found',
  [APP_PATHS.DASHBOARD]: 'No Dashboard Found',
  [APP_PATHS.HOME]: 'No Home Found',
  [APP_PATHS.TUTORIALS]: 'No Tutorials Found',
  [APP_PATHS.ACADEMY]: 'No Academy Found',
  [APP_PATHS.TOP_CREATORS]: 'No Top Creators Found',
  [APP_PATHS.BILLING]: 'No Billing Found',
  [APP_PATHS.SUPPORT]: 'No Support Found',
  [APP_PATHS.FEEDBACK]: 'No Feedback Found',
  [APP_PATHS.UPGRADE]: 'No Upgrade Found',
  [APP_PATHS.TRENDING_POSTS]: 'No Trending Posts Found',
  [APP_PATHS.LIKED]: 'No Liked Items Found'
};
