import { APP_PATHS } from './feature-paths';

export const LOADING_TEXTS: Record<APP_PATHS, string> = {
  [APP_PATHS.HOME]: 'Curating...',
  [APP_PATHS.FOLLOWING]: 'Loading Followings',
  [APP_PATHS.LIKED]: 'Syncing your favorites',
  [APP_PATHS.NOTIFICATIONS]: 'Fetching Notifications',
  [APP_PATHS.LIKED_PICTURES]: 'Loading Your Gallery',
  [APP_PATHS.LIKED_POSTS]: 'Syncing Feed',
  [APP_PATHS.LIKED_VAULTS]: 'Accessing Vaults',
  [APP_PATHS.PROFILE]: 'Loading Profile',
  [APP_PATHS.CREATORS]: 'Ranking Creators',
  [APP_PATHS.CATEGORIES]: 'Scanning Categories',
  [APP_PATHS.POSTS]: 'Scanning Social Pulse',
  [APP_PATHS.PURCHASED]: 'Scanning Collection',
  [APP_PATHS.REPORTS]: 'Verifying Integrity...',
  [APP_PATHS.DASHBOARD]: 'Scanning...',
  [APP_PATHS.SHORTS]: 'Syncing Reels',
  [APP_PATHS.TRENDING]: 'Analyzing Trends',
  [APP_PATHS.TRENDING_CREATORS]: 'Ranking Creators',
  [APP_PATHS.TRENDING_PICTURES]: 'Scanning Lenses',
  [APP_PATHS.TRENDING_VAULTS]: 'Scanning Vaults',
  [APP_PATHS.TRENDING_POSTS]: 'Scanning Feed',
  [APP_PATHS.SUBSCRIPTIONS]: 'Loading Subscriptions',
  [APP_PATHS.HISTORY]: 'Loading History',
  [APP_PATHS.VAULTS]: 'Loading Vaults',
  [APP_PATHS.CHANNELS]: 'Loading Channels',
  [APP_PATHS.PICTURES]: 'Scanning Pictures',
  [APP_PATHS.TUTORIALS]: 'Loading Tutorials',
  [APP_PATHS.ACADEMY]: 'Loading Academy',
  [APP_PATHS.TOP_CREATORS]: 'Loading Top Creators',
  [APP_PATHS.UPGRADE]: 'Loading Upgrade',
  [APP_PATHS.BILLING]: 'Loading Billing',
  [APP_PATHS.SETTINGS]: 'Loading Settings',
  [APP_PATHS.SUPPORT]: 'Loading Support',
  [APP_PATHS.FEEDBACK]: 'Loading Feedback'
};
